######################################################################
# Automatically generated by qmake (2.01a) dom dic 13 20:56:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
